# Generated by Django 4.2.6 on 2023-12-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('son', models.IntegerField()),
                ('img', models.ImageField(upload_to='Courses/img')),
            ],
        ),
    ]
