# Generated by Django 4.2.6 on 2023-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('son', models.IntegerField()),
                ('img', models.ImageField(upload_to='Courses/img')),
            ],
        ),
    ]
