# Generated by Django 4.2.6 on 2023-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='popcourses',
            name='hour',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
