# Generated by Django 4.2.6 on 2023-12-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('img', models.ImageField(upload_to='Testimonial/img')),
            ],
        ),
    ]
