# Generated by Django 4.2.6 on 2023-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_courses1_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
